### ISSUE TITLE
Suggestion: Consolidate README locations

### ISSUE THREAD

**Issue by torischuyler** [domainic/domainic#143]
## Problem

Currently, there are two identical README files located at `docs/experiments/domainic-type-alpha-3` and `docs/experiments/domainic-type-alpha-3/README.md`. This redundancy can cause confusion about which file is the primary source of information.

## Proposed Solution

Consolidate the README files into a single location: `docs/experiments/domainic-type-alpha-3/README.md`. This will streamline the repository structure and make it clear where to find the project's documentation.

## Alternative Solutions

1. **Keep Both but Link**: Maintain both files, but add a note in the `docs/experiments/domainic-type-alpha-3` README directing users to `docs/experiments/domainic-type-alpha-3/README.md` for the primary documentation.
2. **Remove One File**: Delete the `docs/experiments/domainic-type-alpha-3` README and keep only the `docs/experiments/domainic-type-alpha-3/README.md`.

## Additional Context

Having a single README file in the standard `README.md` location under the project directory is a common practice in GitHub repositories. This makes navigation easier for contributors and users alike. If there's a specific reason for keeping both files, it might be worth discussing in the comments.

**Comment by aaronmallen** [comment]
The docs folder in the repo can be confusing to navigate because of the way GitHub handles README.md inside of a directory. It will allow you to both go to the README.md directly AND display it when your in the directory root. It might be a better reading experience via the [wiki](https://github.com/domainic/domainic/wiki/experiments-domainic-type-alpha-3)
